FROM ubuntu:16.04

RUN apt-get update \
    && apt-get -y install \
        software-properties-common

RUN add-apt-repository ppa:builds/sphinxsearch-rel22 \
    && apt-get update \
    && apt-get -y install \
        mysql-client \
        unixodbc \
        libpq5 \
        libmysqlclient-dev \
        libre2-1v5 \
        libre2-dev \
        wget \
    && apt-get remove -y software-properties-common \
    && apt-get autoremove -y \
    && apt-get autoclean \
    && rm -r /var/lib/apt/lists/*

#RUN ln -sf /dev/stdout /var/log/sphinxsearch/searchd.log \
#    && ln -sf /dev/stderr /var/log/sphinxsearch/query.log

COPY sphinx.deb /tmp/sphinx.deb
RUN dpkg -i /tmp/sphinx.deb

COPY start.sh /start.sh
RUN chmod +x /start.sh

VOLUME ["/usr/local/etc"]
VOLUME ["/usr/local/var/data"]

EXPOSE 9312 9306

CMD ["/start.sh"]
